version: "2.1"

services:

  dev:
    image: nginx:alpine
    volumes:
      - "${CONTENT_DIR:-./public}:/usr/share/nginx/html"
    ports:
      - 80:80

  web:
    image: nginx:alpine
    restart: always
    networks:
      - traefik
    volumes:
      - "${CONTENT_DIR:-./public}:/usr/share/nginx/html"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=${HOSTNAME:-demo.approov.io}"
      - "traefik.docker.network=traefik"
      - "traefik.port=80"
      # Low-priority catch-all rule to direct all undefined (sub-)domains to the default demo server home page
      - "traefik.frontend.rule=HostRegexp:{dummy:.*}"
      - "traefik.frontend.priority=1"

networks:
  traefik:
    external: true
